services:
  pangolin:
    image: fosrl/pangolin:latest
    restart: unless-stopped
    volumes:
      - ./config/:/app/config
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/v1/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    environment:
      - NODE_ENV=production
      - ENVIRONMENT=prod
      - DB_TYPE=sqlite
    expose:
      - "3000"
      - "3001"
      - "3002"

  gerbil:
    image: fosrl/gerbil:latest
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config/:/var/config   # <-- use same host config directory!
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    expose:
      - "3003"
      - "3000"
      - "3001"
      - "3002"

volumes:
  # pangolin_config:  <-- REMOVE this named volume, it's not needed here

networks:
  default:
    driver: bridge
    name: pangolin
