services:
  pangolin:
    image: fosrl/pangolin:latest
    container_name: pangolin
    restart: always
    volumes:
      - ./config:/app/config
    environment:
      # Optional, will be automatically replaced by Coolify's internal network DNS
      - INTERNAL_HOSTNAME=pangolin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: 3s
      timeout: 3s
      retries: 5

  gerbil:
    image: fosrl/gerbil:latest
    container_name: gerbil
    restart: always
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://pangolin:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - ./config:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: always
    network_mode: service:gerbil
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./config/traefik:/etc/traefik:ro
      - ./config/traefik:/letsencrypt
    labels:
      # Coolify-specific labels for routing, will be set automatically
      - "coolify.managed=true"
      - "coolify.applicationId=9"
      - "coolify.type=application"

