app:
  dashboard_url: "https://pang-api.irma-prod.net"

domains:
  domain1:
    base_domain: "pangolin.irma-prod.net"
    cert_resolver: "letsencrypt"
  domain2:
    base_domain: "pang-api.irma-prod.net"
    cert_resolver: "letsencrypt"
server:
  secret: "rG7#xN8!sY2@LqP4$eR9&UkM1*WdC6^Zf"

gerbil:
  base_endpoint: "pang-api.irma-prod.net"

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: true